.\" man page for libstash
.\" Contact webb.clint@gmail.com to correct errors or omissions. 
.TH stash_init 3 "25 October 2010" "0.07.00" "libstash - Library for accessing a Stash data storage service."
.SH NAME
stash_init - Initialise the stash_t object.
.SH SYNOPSIS
#include <stash.h>
.sp
.B stash_t * stash_init(stash_t *stash);
.br
.SH DESCRIPTION
.B stash_init()
is used to initialise a stash object, or create one if the parameter is NULL.  It will return a pointer to an initialised stash object, that will then be used for most stash operations.
.B stash_free() 
is used to free up all the resources allocated in the stash object, and if the stash object was created by stash_init(), it will free up the stash object too.
.br
.SH EXAMPLE
.SS "Letting stash create itself"
.nf
#include <stash.h>

int main(void) {
  stash_t *stash;

  stash = stash_init(NULL);
  // do something with stash... 
  stash_free(stash);

  return 0;
}
.fi
.SS "Initializing an existing object"
.nf
#include <stash.h>

int main(void) {
  stash_t stashobj;

  stash_init(&stashobj);
  // do something with stash... 
  stash_free(&stashobj);

  return 0;
}
.fi

.SH "SEE ALSO"
.BR stash_free (3),
.BR stash_t (3),
.BR libstash (3)
.SH AUTHOR
.nf
Clint Webb (webb.clint@gmail.com)
.fi
