.\" man page for libstash
.\" Contact webb.clint@gmail.com to correct errors or omissions. 
.TH stash_sortentry_t 3 "16 November 2010" "0.07.00" "libstash - Library for accessing a Stash data storage service."
.SH NAME
stash_sortentry_t - stash sort rule object.
.SH DESCRIPTION
.B stash_sortentry_t
is a structure that is used to apply sort rules to queries.  
.SS Initialization 
.B stash_sortentry_t(kid, desc, next)
is used to create a new sort entry object.  It very simply will contain the Key to sort on, descending (1 or 0 for ascending), and a pointer to another sort entry to be used if the key values are the same.
.SS Cleanup
.B stash_sortentry_free() 
is used to free up all the resources allocated with the query (but not the result).
.sp
This structure is also used internally for the sort rules on queries.
.br
.SH "SEE ALSO"
.BR stash_sortentry (3),
.BR stash_sortentry_free (3).
.SH AUTHOR
.nf
Clint Webb (webb.clint@gmail.com)
.fi
